language: ruby
bundler_args: --without system_tests
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
script: "bundle exec metadata-json-lint --strict-license --fail-on-warnings metadata.json && bundle exec rake ci SPEC_OPTS='--format documentation'"
branches:
  only:
    - master
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.7.0"
    - PUPPET_GEM_VERSION="~> 3.7.0" FUTURE_PARSER="yes" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 3.7.0" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
matrix:
  fast_finish: true
notifications:
  email: false
gemfile: Gemfile
