language: ruby
sudo: false
bundler_args: --without system_tests
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
script: "bundle exec metadata-json-lint --strict-license --fail-on-warnings metadata.json && bundle exec rake ci SPEC_OPTS='--format documentation'"
branches:
  only:
    - master
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.7.0"
    - PUPPET_GEM_VERSION="~> 3.7.0" FUTURE_PARSER="yes" STRICT_VARIABLES="no"
    - PUPPET_GEM_VERSION="~> 3.7.0" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
    - PUPPET_GEM_VERSION="~> 4.0.0"
    - PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES="yes"
matrix:
  fast_finish: true
  include:
    - rvm: default
      sudo: required
      dist: trusty
      services: docker
      env: BEAKER_set="centos-7_docker"
      bundler_args:
      script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance
notifications:
  email: false
gemfile: Gemfile
